### ISSUE TITLE
Throwing error on flags.log.split()

### ISSUE THREAD

**Issue by miguelmota** [webcomponents/webcomponentsjs#180]
`flags.log` is an object

![screen shot 2015-01-29 at 1 22 52 pm](https://cloud.githubusercontent.com/assets/168240/5966529/28efc7c8-a7ba-11e4-8a88-9cccd855eb39.png)
![screen shot 2015-01-29 at 1 23 06 pm](https://cloud.githubusercontent.com/assets/168240/5966530/2900d8f6-a7ba-11e4-892b-8176ec6e669a.png)

**Comment by miguelmota** [comment]
Fixed by moving script to head.

**Comment by addyosmani** [comment]
Thanks for reporting back.

**Comment by ComFreek** [comment]
This also happened to me. In my case I even had to move the `<script>` tag before all the `<link>` tags I had.

**Comment by Dade3007** [comment]
I'm still having the problem. I put the webcomponents.js script the first of all, but still having the error.

**Comment by nislowk** [comment]
also having this issue.  Went away in a recent version of webcomponents.js but came back

**Comment by igorspasic** [comment]
Also having the issue.

**Comment by MauriceSchoenmakers** [comment]
maybe but it is still an errer IMHO

**Comment by garlicnation** [comment]
https://github.com/webcomponents/webcomponentsjs/pull/223

**Comment by garlicnation** [comment]
Fixed in #223. Reopen after the next release(Tenatively march 15th) if this reoccurs.

**Comment by dtracers** [comment]
is #223 in the 6.0 release?

Because I downloaded 6.0 via bower and manually but am still experiencing this error.

Specifically it is saying on line 30 of the webcomponentjs is not a function

```
if (flags.log) {
    var parts = flags.log.split(",");
```

This is what is in the file but I feel it is supposed to be

```
if (flags.log && flags.log.split) {
```

**Comment by ballerabdude** [comment]
@dtracers this is what im doing and its currently working except this version injects script tags into the dom. With the above fix other developers wont be able to see your bug fix in your node_moudle because its generally ignored.  
```javascript
"webcomponentsjs": "git@github.com:webcomponents/webcomponentsjs.git#58c870917c838846fb7f4c9ec72941c2358562cc"
