### ISSUE TITLE
Shadow CSS is not re-basing relative urls from original css file location

### ISSUE THREAD

**Issue by pflannery** [webcomponents/webcomponentsjs#211]
html snippet

``` html
<link rel="stylesheet" href="assets/css/file.css" shim-shadowdom>
```

original css snippet

``` css
@font-face {
    font-family: 'test family';
    src: url('../fonts/test.eot'); // should resolve to assets/fonts/test.eot
}
```

after conversion snippet

``` css
@font-face {
    font-family: 'test family';
    src: url('[absolute-url]/fonts/test.eot'); // instead its getting based from the loading html file
}
```

The reason is that the original stylesheet href is not used as the resolver [source code here](https://github.com/webcomponents/webcomponentsjs/blob/master/src/ShadowCSS/ShadowCSS.js#L745) , instead its using a blank `a` element href [source code here](https://github.com/webcomponents/webcomponentsjs/blob/e49de932c97ec336c6e1b106319a582e07d7385d/src/HTMLImports/path.js#L21)

It also ignores if the url is a relative path or not. [source code here](https://github.com/webcomponents/webcomponentsjs/blob/e49de932c97ec336c6e1b106319a582e07d7385d/src/HTMLImports/path.js#L34-L37)

**Comment by pflannery** [comment]
I believe something like this would fix it:

**uses the stylesheet as the resolver** (though im not 100% if elt will always be a stylesheet, need to clarify)
```js
style.textContent = HTMLImports.path.resolveUrlsInCssText(style.textContent, elt); 
```

**captures absolute or relative paths when replacing the url's** (provided were using a stylesheet href to resolve)
```js
  function replaceUrls(text, urlObj, regexp) {
    var strippedFileNameUrl = urlObj.href.substring(0, urlObj.href.lastIndexOf("/")+1);
    return text.replace(regexp, function(m, pre, url, post) {
      var urlPath = url.replace(/["']/g, '');
      if (urlPath.indexOf('..') > -1) {
        urlObj.href = strippedFileNameUrl + urlPath;
        urlPath = urlObj.href;
      }
      return pre + '\'' + urlPath + '\'' + post;
    });
  }
```

**Comment by addyosmani** [comment]
> uses the stylesheet as the resolver (though im not 100% if elt will always be a stylesheet, need to clarify)

Were you able to verify this?

**Comment by pflannery** [comment]
just revisited this and it was fixed in this [commit](https://github.com/webcomponents/webcomponentsjs/commit/4c5f21610c6cea02c74beaa3a25cd8075807ce31)

:+1:

**Comment by pflannery** [comment]
damn need to re-open, I've found a bug in IE 

`SCRIPT445: Object doesn't support this action` 

at this [line](https://github.com/webcomponents/webcomponentsjs/blob/master/src/HTMLImports/path.js#L36)

`urlPath = (new URL(urlPath, linkUrl)).href;`

This seems like a similar issue to #53

**Comment by eugef** [comment]
I still see this issue in IE11.

IE11 first tries to resolve url font from the document location and gets 404 (/fonts/test.eot)
Then it resolves url relative to css (/fonts/test.eot) and loads the font correctly.

In the same css I have relative path to the image, but it works fine.

**Comment by akstek** [comment]
Hm, will this bug be resolved in the near future? Still stuck with Polymer 2.1 and webcomponents.js 1.0.1 cause we cant update our project.

**Comment by TimvdLippe** [comment]
Thanks for the issue. It has been a great while since this issue was opened. Sadly, this issue misses a live reproduction with the most recent version of the webcomponents polyfill for us to be able to debug and potentially fix. Versions 1 of the polyfills fix a large amount of issues, probably including this one as well.

Please see [the CONTRIBUTING.md](https://github.com/webcomponents/webcomponentsjs/blob/master/CONTRIBUTING.md) for guidelines on filing issues.  You can start from [this jsBin template](http://jsbin.com/birajez/edit?html,console,output) as a starting point and link it in the issue template under "Live Demo".

Feel free to file a new issue following these instructions if you can still reproduce this issue with versions 1 of the polyfills.  Thank you!
