### ISSUE TITLE
registerElement is not a function in Firefox

### ISSUE THREAD

**Issue by mhusm** [webcomponents/webcomponentsjs#699]
The newest release candidate produces the following error in Firefox.

> TypeError: document.registerElement is not a function

See this [question](http://stackoverflow.com/questions/42526642/polymer-sample-code-not-working-in-firefox/42527803#42527803) on Stackoverflow.
This  also results in the [plunk](https://plnkr.co/edit/QfsudzAPCbAu56Qpb7eB?p=preview) linked from the [docs](https://www.polymer-project.org/1.0/start/first-element/intro) not working currently.

**Comment by cdchase** [comment]
Are you sure you are waiting for polyfill to load before creating elements? I had the same problem and moved my element creation inside:
```
window.addEventListener('WebComponentsReady', function(e) {
  // Create elements here
}
```
And this error went away... still chasing another, but thought I would suggest this.

**Comment by mhusm** [comment]
It looks like this has been fixed. The plunk from the docs is working again. I think the problem was Polygit serving the latest version of webcomponents by default, which was not compatible with Polymer 1.0, as is explained in the referenced issue above. Right now I'm receiving v0.7.24 for https://polygit.org/components/webcomponentsjs/webcomponents-lite.js and it works fine.

**Comment by cdchase** [comment]
The error came back for me, and after digging deeper, I discovered that _document.registerElement_ should now be: **customElements.define**

**Comment by mhusm** [comment]
Are you working with Polymer v1.? Then you have to make sure to use a v0.x for the webcomponents polyfill. v1.x only works with Polymer v2.x.

**Comment by cdchase** [comment]
Not using Polymer at all actually. Just the polyfills for local webcomponents.

I got pulled away from this work in the middle of conversion from v0 to v1 of webcomponents, and had not completed the updates all-around. Wanted to use the latest to get the best support for alternate browsers, but find we are limited by our current use of Firefox ESR 45. Once that is updated to ESR 52, I'll be able to try this again.  :-)

**Comment by mhusm** [comment]
:) I sometimes forget that there are other ways to use web components than Polymer

**Comment by netpoetica** [comment]
I ran `bower install --save webcomponents/webcomponentsjs` and when I use

```
<!-- Load polyfills; note that "loader" will load these async -->
    <script src="bower_components/webcomponentsjs/webcomponents-loader.js"></script>
```

I get this same error in both Firefox and Safari when trying to load my page with custom elements:

```
TypeError: thatDoc.registerElement is not a function
```

I also am not using this with Polymer. Was this ever solved?

**Comment by web-padawan** [comment]
@netpoetica that is the old ALI, and you need to use the `v0` branch for that, see the note in readme.

**Comment by netpoetica** [comment]
Thank you - I just realized the error was caused by the lib that I was using, not by this one. Sorry for bugging you! Thanks again
