### ISSUE TITLE
Not working in IE11

### ISSUE THREAD

**Issue by Mikanoshi** [webcomponents/webcomponentsjs#72]
https://www.polymer-project.org/docs/start/getting-the-code.html
```
Unable to get property 'getItem' of undefined or null reference
File: webcomponents.min.js, Line: 11, Column: 13157
```

My project (works in Firefox/Chrome):
```
Unable to get property 'addEventListener' of undefined or null reference
File: webcomponents.js, Line: 957, Column: 9
```
```
Exception caught during observer callback: Error: Invalid argument.
   at data.set (http://sysprofile.ru/polymer/bower_components/webcomponentsjs/webcomponents.js:2292:9)
   at updateText (http://sysprofile.ru/polymer/elements.js:3:25733)
   at Anonymous function (http://sysprofile.ru/polymer/elements.js:3:25814)
   at ObserverTransform.prototype.observedCallback_ (http://sysprofile.ru/polymer/elements.js:3:16463)
   at Observer.prototype.report_ (http://sysprofile.ru/polymer/elements.js:3:8607)
   at check_ (http://sysprofile.ru/polymer/elements.js:3:15708)
   at global.Platform.performMicrotaskCheckpoint (http://sysprofile.ru/polymer/elements.js:3:9568)
   at Anonymous function (http://sysprofile.ru/polymer/elements.js:5:1948)
   at atEndOfMicrotask (http://sysprofile.ru/polymer/elements.js:5:1281)
   at notifyObservers (http://sysprofile.ru/polymer/bower_components/webcomponentsjs/webcomponents.js:578:13)
```

I'm using 0.5.1-1 release with these elements vulcanized:
```
<link rel="import" href="bower_components/polymer/polymer.html">

<link rel="import" href="bower_components/core-style/core-style.html">
<link rel="import" href="bower_components/core-transition/core-transition.html">
<link rel="import" href="bower_components/core-menu/core-menu.html">
<link rel="import" href="bower_components/core-pages/core-pages.html">

<link rel="import" href="bower_components/paper-button/paper-button.html">
<link rel="import" href="bower_components/paper-input/paper-input.html">
<link rel="import" href="bower_components/paper-tabs/paper-tabs.html">
<link rel="import" href="bower_components/paper-dialog/paper-dialog.html">
<link rel="import" href="bower_components/paper-dialog/paper-dialog-transition.html">
<link rel="import" href="bower_components/paper-dropdown/paper-dropdown.html">
<link rel="import" href="bower_components/paper-dropdown-menu/paper-dropdown-menu.html">
<link rel="import" href="bower_components/paper-slider/paper-slider.html">
<link rel="import" href="bower_components/paper-checkbox/paper-checkbox.html">
```

**Comment by silentHoo** [comment]
+1

**Comment by garlicnation** [comment]
0.5.1 contains numerous issues since resolved in 0.5.4.

Are you experiencing this issue in 0.5.4?

**Comment by Mikanoshi** [comment]
Yes, all those errors are on 0.5.4, getting-the-code.html is still broken too (navigation is not working).
My project is working though despite the error.

**Comment by garlicnation** [comment]
Closing - getting-the-code.html now works in IE11.

**Comment by Mikanoshi** [comment]
Paper and core elements sections are still not working. Even selecting a working section makes the whole left panel unresponsive, so nothing can be clicked anymore...

**Comment by garlicnation** [comment]
@Mikanoshi The issues you reported are fixed, but there are some lingering issues in IE11. I opened Polymer/docs#962 to track them.
