### ISSUE TITLE
setting textContent of a document fragment to an empty string should remove all its content

### ISSUE THREAD

**Issue by vlukashov** [webcomponents/webcomponentsjs#754]
The spec [says](https://developer.mozilla.org/en-US/docs/Web/API/Node/textContent#Description) that setting the `textContent` of a document fragment to an empty string should remove all its content.

Example:
```javascript
let fragment = document.createDocumentFragment();
fragment.appendChild( document.createElement( 'div' ) );
console.log(fragment.childElementCount); // prints 1

fragment.textContent = '';
console.log(fragment.childElementCount); // prints 0
```

When the Shady DOM v1 polyfill is active that's no longer the case:
```javascript
let fragment = document.createDocumentFragment();
fragment.appendChild( document.createElement( 'div' ) );
console.log(fragment.childElementCount); // prints 1

fragment.textContent = '';
console.log(fragment.childElementCount); // still prints 1
```

# Why bother?

There are some popular JS libraries (including jQuery) that rely on this behavior. At least, the latest versions jQuery 2.x and 3.x are affected. [Here](https://github.com/vlukashov/shady-dom-set-text-content) is a demo page for this issue.

# Affected versions

The bug can be reproduced on the latest version of webcomponentsjs (1.0.0-rc.7 at the time of submitting the issue).

# Demo

[https://github.com/vlukashov/shady-dom-set-text-content](https://github.com/vlukashov/shady-dom-set-text-content)

**Comment by RevillWeb** [comment]
Hi,

We are seeing the same issue in a AngularJS 1.x application which is preventing any directive from loading basically rendering our application useless.

A colleague of mine has put together a demo which can be found here:  https://revillweb.github.io/angular-shadydom-issue/ 

Any updates on this issue would be highly appreciated. Thank you.

**Comment by CaptainCodeman** [comment]
I hit the same issue (also jQuery / Angular 1 related) https://github.com/webcomponents/webcomponentsjs/issues/777

Just got to the same point and found this.

**Comment by sorvell** [comment]
Fixed via https://github.com/webcomponents/shadydom/pull/164.

**Comment by bwolff** [comment]
Hi,

as already mention in  webcomponents/shadydom#164, I can still reproduce this issue with the latest release webcomponentsjs 1.0.4. It looks to me like the referenced issue was not properly merged.

Can anybody confirm that this issue still persists in the latest webcomponentsjs release? It's quite a blocker for us, as it breaks some jQuery based plugins (e.g. Bootstrap Modal dialogs and notifier). Having this fixed would allow us to move to Polymer 2.0.

Thanks for double checking.

Cheers,
Ben
