### ISSUE TITLE
Element.insertAdjacentElement on Firefox 42 

### ISSUE THREAD

**Issue by oravecz** [webcomponents/webcomponentsjs#829]
Results in following warning when `webcomponents-lite.js` is loaded. 

```
Custom Elements: `Element#insertAdjacentElement` was not patched.
```

What is the patch supposed to do? 
Is this a concern?

**Comment by TimvdLippe** [comment]
This has been fixed with https://github.com/webcomponents/custom-elements/pull/147

**Comment by LostInBrittany** [comment]
Hey @TimvdLippe I still get the same error on Firefox 38, using webcomponents/webcomponentsjs 2.0.2 (that includes webcomponents/custom-elements 1.1.2, which seems to include this patch...).

Any idea?

**Comment by TimvdLippe** [comment]
@lostinbrittany Please open a new issue with a JSBin that shows the problem in the correct repo :)

**Comment by LostInBrittany** [comment]
Isn't this one the correct repo? I have the problem with webcomponents/webcomponentsjs :)

**Comment by TimvdLippe** [comment]
It loads separate polyfills. E.g. webcomponents/custom-elements does custom elements. Webcomponents/shadydom mimics shadow dom, etc...

**Comment by LostInBrittany** [comment]
Oh, ok, so I should do a testcase using only custom-elements polyfill, and post on their repo... Thanks!
