### ISSUE TITLE
v2.1.1 webpack and IE11

### ISSUE THREAD

**Issue by cbonnissent** [webcomponents/webcomponentsjs#993]
The version 2.1.1 doesn't work on IE11 when it's compiled with webpack.

I have the following error :

> Symbol est indéfini (Symbol is undefined)

It works well with the version 2.0.2

**Comment by TimvdLippe** [comment]
This should now be fixed in #1005.

**Comment by LarsDenBakker** [comment]
@TimvdLippe I'm still getting errors on IE11 with 2.1.3:

![screen shot 2018-10-07 at 5 00 11 pm](https://user-images.githubusercontent.com/11994993/46583162-85758280-ca52-11e8-8cf3-93c0b62c9c6d.png)

Using 2.1.0 I don't get this error.

In my setup I first load webcomponents-loader, then my app which includes the babel polyfills.

**Comment by web-padawan** [comment]
@ruphin FYI this happened to me also when placing polyfill in tests before WCT script. Appears to be related to Symbol polyfill.

**Comment by ruphin** [comment]
Thanks for the report, I will look into it.

**Comment by LarsDenBakker** [comment]
The problem went away when I load the babel polyfills before webcomponentsjs. Most likely because then webcomponentsjs skips it's internal polyfills.

**Comment by ruphin** [comment]
I think it's a good pattern in general to load babel polyfills before loading anything else, to avoid problems like this. Clearly the babel polyfill is not compatible with the polyfills included in webcomponentsjs, and it overrides the existing implementation for some reason, breaking things.

I think it's a good idea to create a webcomponentsjs bundle that assumes the presence of babel-polyfill, while the regular webcomponentsjs bundles can be used as standalone items.
